### ISSUE TITLE
Examples partially work with `dnf` (Fedora)

### ISSUE THREAD

**Issue by jwinarske** [canonical/packagekit.dart#11]
```
$ dart example.dart 
Server version: 1.2.4
Backend: Dnf (dnf)
Supported MIME types: application/x-rpm
```

```
$ dart get_updates.dart 
Unhandled exception:
RangeError (index): Invalid value: Not in inclusive range 0..25: 327688
#0      List.[] (dart:core-patch/array.dart:282:36)
#1      new PackageKitTransaction.<anonymous closure> (package:packagekit/src/packagekit_client.dart:651:40)
#2      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
#3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

```
$ dart update.dart 
Unhandled exception:
RangeError (index): Invalid value: Not in inclusive range 0..25: 327688
#0      List.[] (dart:core-patch/array.dart:282:36)
#1      new PackageKitTransaction.<anonymous closure> (package:packagekit/src/packagekit_client.dart:651:40)
#2      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
#3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

```
$ dart depends_on.dart bazel
Unhandled exception:
org.freedesktop.PackageKit.Transaction.NotSupported: DependsOn not supported by backend
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1132:9)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:609:12)
<asynchronous suspension>
#2      PackageKitTransaction.dependsOn (package:packagekit/src/packagekit_client.dart:685:5)
<asynchronous suspension>
#3      main (file:///home/runner/packagekit.dart/example/depends_on.dart:50:3)
<asynchronous suspension>
```

**Comment by robert-ancell** [comment]
The first two cases are the dnf backend returning invalid enumerated values, which is now handled in 2bb7b8bd991bdb2375436d62be7c07a8cd8fdf43. The latter case is an error coming from the backend which indicates dnf doesn't support the depends on request. Hope this helps!

**Comment by jwinarske** [comment]
@robert-ancell Awesome thanks!
